urls.py
from django.conf.urls import url

from . import views

app_name = 'slas'

urlpatterns = [
    url(r'^$', views.index, name='slas'),
    url(r'^inscription/(?P<activity_id>[0-9]+)$', views.inscription, name='inscription'),
    url(r'^add_student/(?P<activity_id>[0-9]+)$', views.add_student, name='add_student'),
    url(r'^check_student/(?P<activity_id>[0-9]+)/(?P<surname>.+?)/(?P<first_name>.+?)$', views.check_student,
        name='check_student'),
    url(r'^payed/(?P<activity_id>[0-9]+)/(?P<payed>[0-9]+)$', views.payed, name='payed'),
    url(r'^payed$', views.payed, name='payed_clean'),
    url(r'^answered/(?P<activity_id>[0-9]+)/(?P<answered>[0-9]+)$', views.answered, name='answered'),
    url(r'^answered', views.payed, name='answered_clean'),
    url(r'^list', views.list_inscriptions, name='list'),
    url(r'^data', views.get_excel_data, name='data'),

]

forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Field, Hidden, HTML, Button
from crispy_forms.bootstrap import FormActions, Tab, TabHolder, Alert

from .models import PAYEMENT_CHOICES

class InscriptionForm(forms.Form):
    student_surname = forms.CharField(
        label='Nom :',
        max_length=200,
        required=True
    )

    student_first_name = forms.CharField(
        label='Prénom :',
        max_length=200,
        required=True
    )

    classe = forms.CharField(
        label='Classe (2020-2021) :',
        max_length=200,
        required=True
    )

    birthdate = forms.CharField(
        label='Date de naissance :',
        max_length=200,
        required=True
    )

    family = forms.CharField(
        label="Autre(s) frère(s) ou sœur(s) inscrit(s) à un atelier (noms et prénoms)",
        max_length=200,
        required=False,
    )

    resp_surname = forms.CharField(
        label='Nom du responsable :',
        max_length=200,
        required=True
    )

    resp_first_name = forms.CharField(
        label='Prénom du responsable :',
        max_length=200,
        required=True
    )

    address = forms.CharField(
        label='Adresse du responsable :',
        max_length=300,
        required=True
    )

    resp_email = forms.EmailField(
        label="Email d'un responsable",
        required=True,
    )

    resp_email_2 = forms.EmailField(
        label="Deuxième email d'un responsable (optionnel)",
        required=False,
    )

    resp_telephone = forms.CharField(
        label="Numéro de téléphone",
        max_length=200,
        required=True,
    )

    resp_telephone_2 = forms.CharField(
        label="Deuxième numéro de téléphone",
        max_length=200,
        required=True,
    )

    resp_payement = forms.ChoiceField(
        label="Fréquence de paiement",
        choices=PAYEMENT_CHOICES,
        widget=forms.RadioSelect,
    )

    confirm = forms.BooleanField(
        label="J'inscris mon enfant à cette activité et confirme avoir pris connaissance des dispositions pratiques.",
        required=True,
    )

    def __init__(self, *args, **kwargs):
        self.description = kwargs.pop('description', "")
        self.activity_id = kwargs.pop('activity_id')
        self.is_free = kwargs.pop('is_free', None)
        self.is_full = kwargs.pop('is_full', False)
        super(InscriptionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.html5_required = True
        self.helper.form_class = 'col-sm-10'
        self.helper.form_id = 'inscription-form'
        # Add alert if is_free
        self.helper.layout = Layout(
            Hidden("activity_id", str(self.activity_id)),
            TabHolder(
                Tab("Activité",
                    HTML("<h4>Description de l'activité :</h4>"),
                    HTML("<p>%s</p>" % (self.description)),
                    Button("next-to-coord_el", "Suivant"),
                    css_id="activity_tabo",
                    ),
                Tab("Élève",
                    Field('student_surname'),
                    Field('student_first_name'),
                    Field('classe'),
                    Field('birthdate'),
                    Field('family'),
                    Button("next-to-coord_resp", "Suivant"),
                    css_id="eleve_tab",
                    ),
                Tab("Responsable",
                    Field('resp_surname'),
                    Field('resp_first_name'),
                    Field('address'),
                    Field('resp_email'),
                    Field('resp_email_2'),
                    Field('resp_telephone', placeholder="04xx xx xx xx"),
                    Field('resp_telephone_2', placeholder="04xx xx xx xx"),
                    Button("next-to-confirm", "Suivant"),
                    css_id="resp_tab",
                    ),
                Tab("Confirmation",
                    Div(
                        Field('resp_payement'),
                        Field("confirm"),
                        FormActions(
                            Submit('submit', 'Soumettre', disabled='true'),
                            Button("cancel", "Annuler"),
                        ),
                        Div(
                            HTML(
                                """
                                <p>Les champs suivants sont manquants ou mal formatés</p>
                                <ul id="fail-list">
                                  <li id="fail-1">Nom de l'élève</li>
                                  <li id="fail-2">Prénom de l'élève</li>
                                  <li id="fail-3">Classe</li>
                                  <li id="fail-4">Date de naissance</li>
                                  <li id="fail-5">Nom du responsable</li>
                                  <li id="fail-6">Prénom du responsable</li>
                                  <li id="fail-7">Adresse</li>
                                  <li id="fail-8">Email 1</li>
                                  <li id="fail-9">Numéro de téléphone 1</li>
                                  <li id="fail-10">Numéro de téléphone 2</li>
                                </ul>
                                """
                                ),
                                css_class="alert alert-danger",
                                css_id="fail",
                                role="alert",
                                style="display:none;margin-top:15px"
                            ),
                        Div(
                            HTML("L'élève est déjà inscrit/renseigné."),
                            css_class="alert alert-danger",
                            css_id="fail_exist",
                            role="alert",
                            style="display:none;margin-top:15px"
                            ),
                        Div(
                            HTML("La demande a bien été envoyé. Merci ! Un email vous a été envoyé. Si vous n'avez reçu aucun email, merci de bien vérifiez vos courriers indésirables."),
                            css_class="alert alert-success",
                            css_id="success",
                            role="alert",
                            style="display:none;margin-top:15px"
                            ),
                        ),
                    css_id="confirm_tab"
                    ),
            )
        )
        if not self.is_free:
            self.helper.layout[1][3][0].insert(1, Div(HTML("Merci d'attendre la réception de la facture avant de payer."),
                                                      css_class="alert alert-danger"))
        if self.is_full:
            self.helper.layout[1].pop(3)
            self.helper.layout[1].pop(2)
            self.helper.layout[1].pop(1)
            self.helper.layout[1][0].pop(2)
            self.helper.layout[1][0].insert(0, Alert(content="L'activité est compléte !", css_class="alert-warning"))

templates/slas/email_confirm.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Confirmation de la demande d'inscription à SLAS</title>
</head>
<body>
<p>Bonjour,</p>
<p>Merci d'avoir fait une demande d'inscription pour {{ full_name }} à l'activité «{{ activity.name }}»
    {% if not activity.is_free %} le {{ activity.day }}{% endif %}.</p>
<p>Nous vous recontacterons début septembre afin de confirmer l'inscription de votre enfant à l'activité.</p>
<p>L'équipe d'After School</p>
<hr>
<p style="color:grey">Ceci est un email automatique, merci de ne pas y répondre. Si vous avez un problème, veuillez contacter <a mailto="info@slas.be">info@slas.be</a>.</p>
</body>
</html>

templates/slas/index.html
<!doctype html>
<html>
    <head>
        {% load staticfiles %}
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'bootstrap3_10columns/css/bootstrap.min.css' %}">
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap3_10columns/js/bootstrap.min.js' %}"></script>
        <link href="{% static 'bootstrap3_datetime/css/bootstrap-datetimepicker.min.css' %}" type="text/css" media="all" rel="stylesheet">
        <script type="text/javascript" src="{% static 'bootstrap3_datetime/js/moment.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap3_datetime/js/bootstrap-datetimepicker.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap3_datetime/js/locale/fr-be.js' %}"></script>
        <style>
            @media (min-width: 800px) {
                .activite-group.non-free {
                    min-height: 330px
                }
            }
        </style>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <h2>Inscription à une activité de l'After School asbl</h2>
                <p>Cliquez sur les différents cours pour vous-y inscrire. Le public ciblé se trouve entre parenthèse (Pr pour «primaire» et Sec pour «secondaire»).</p>
                <p>Pour toute information complémentaire, veuillez contacter Anne Chalon à l'adresse suivante <a href="mailto:info@slas.be">info@slas.be</a> ou téléphoner au 0497/06 71 39.</p>
            </div>
            <div class="row" style="text-align: center;">
                <h4>Inscrire un élève à une activité :</h4>
                {% for day in activities %}
                <div class="col-sm-2">
                  <h3>{{ day.0.0.day }}</h3>
                  {% for slot in day %}
                  <div class="activite-group non-free">
                    <h4>
                        {% if slot.0.day != 'Mercredi' and slot.0.day != 'Vendredi' and slot|length > 0 %}
                            {% if not slot.0.slot %}16h20 à 17h10{% else %}17h10 à 18h00{% endif %}
                        {% elif slot.0.day == 'Vendredi' %}
                            {% if not slot.0.slot %}15h20 à 16h10{% else %}16h20 à 17h10{% endif %}
                        {% else %}
                            
                        {% endif %}
                    </h4>
                    {% for act in slot %}
                    {% if not act.is_hidden %}
                    {% if act.day == 'Mercredi' %}
                    <div style="font-weight:bold;">
                        <p>12h40 - 13h10 : Repas</p>
                        <p>13h10 - 14h10 : étude/lecture/jeux société</p>
                    </div> 
                    {% endif %}
                    {% if act.day == 'Mercredi' %}
                    <div class="row">
                        <div class="col-xs-7" style="padding-right:5px">
                        {% endif %}
                            <div class="panel panel-warning">
                                <div class="panel-heading">
                                    {% if act.day == 'Mercredi' %}<strong>14h20 à 16h10</strong><br />{% endif %}
                                    {% if not act.is_disabled %}<a data-toggle="modal" href="{% url 'slas:inscription' act.pk %}" data-target="#myMod"
                                    data-remote="false" onclick="">{% endif %}
                                    {{ act.name }} ({{ act.age }})
                                    {% if not act.is_disabled %}</a>{% endif %}
                                </div>
                            </div>
                        {% if act.day == 'Mercredi' %}
                        </div>
                        <div class="col-xs-3" style="font-weight:bold;padding-left:0px;padding-right:5px">
                            <p style="margin-top:15px;">Garderie 1 période > 15h10</p>
                            <p style="margin-top:15px;">Garderie 1 période > 16h10</p>
                        </div>
                    </div>
                    {% endif %}
                    {% if act.day == 'Mercredi' %}
                    <div style="font-weight:bold;">
                        <p>Garderie 1 période jusqu’à 17h</p>
                        <p>Garderie 1 période jusqu’à 18h</p>
                    </div> 
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                  </div>
                  {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    <div class="modal fade" id="myMod" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4></h4>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>
    <script>
        $("#myMod").on("show.bs.modal", function(e) {
            var link = $(e.relatedTarget);
            $(this).find(".modal-body").load(link.attr("href"));
        });
        //changeModelHeader('S\'inscrire à l'activité');
    </script>
    </body>
</html>

templates/slas/inscription.html
<div class="row">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    {% crispy form %}
</div>
<script>
    var activity_id = $('input[name="activity_id"]').val()
    var lock = false;
    $('#id_birthdate').datetimepicker({
        //defaultDate: moment("2005-01-01"),
        format: 'YYYY-MM-DD',
        viewMode: 'years',
        locale: 'fr',
        sideBySide: false,
        allowInputToggle: true
    });

    $('#button-id-next-to-coord_el').click( function () {
        $('li.tab-pane a:eq(1)').tab('show');
    });
    $('#button-id-next-to-coord_resp').click( function () {
        $('li.tab-pane a:eq(2)').tab('show');
    });
    $('#button-id-next-to-confirm').click( function () {
        $('li.tab-pane a:eq(3)').tab('show');
    });

    $('#button-id-cancel').click( function () {
        $('#myMod').modal('hide');
    });

    $('#id_confirm').change( function() {
        if (this.checked) {
          $("#submit-id-submit").removeAttr("disabled");
        } else {
          $("#submit-id-submit").attr("disabled", "disabled");
        }
      });

    function testEmail(email) {
        return new RegExp(/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/).test(email);
    }

    function checkForm() {
        $('#fail_exist').hide();
        $('#fail-list li').hide();

        var isOk = true;
        if ($('#id_student_surname').val() == "") {
          isOk = false;
          $('#fail-1').show();
        }
        if ($('#id_student_first_name').val() == "") {
          isOk = false;
          $('#fail-2').show();
        }
        if ($('#id_classe').val() == "") {
          isOk = false;
          $('#fail-3').show();
        }
        if ($('#id_birthdate').val() == "") {
          isOk = false;
          $('#fail-4').show();
        }
        if ($('#id_resp_surname').val() == "") {
          isOk = false;
          $('#fail-5').show();
        }
        if ($('#id_resp_first_name').val() == "") {
          isOk = false;
          $('#fail-6').show();
        }
        if ($('#id_address').val() == "") {
          isOk = false;
          $('#fail-7').show();
        }
        if ($('#id_resp_email').val() == "" || !testEmail($('#id_resp_email').val())) {
          isOk = false;
          $('#fail-8').show();
        }
        if ($('#id_resp_telephone').val() == "") {
          isOk = false;
          $('#fail-9').show();
        }
        if ($('#id_resp_telephone_2').val() == "") {
          isOk = false;
          $('#fail-10').show();
        }

        if (!isOk) {
            $("#fail").fadeIn();
        } else {
            $("#fail").fadeOut();
        }

        return isOk;
    }

    $("#submit-id-submit").click(function (e) {
        e.preventDefault();
        if (lock) return;

        lock = true;
        $('#success').hide();
        $('#submit-id-submit').removeAttr('disabled').val("Demande en cours…");
        var is_form_ok = checkForm();
        if (is_form_ok) {
            var surname = $('#id_student_surname').val();
            var first_name = $('#id_student_first_name').val();
            $.get("check_student/" + activity_id + "/" + surname + "/" + first_name, function(data) {
                if (data == "0") {
                    $("#fail_exist").hide();
                    $.ajax({
                        type: 'POST',
                        url: 'add_student/' + activity_id,
                        data: $('#inscription-form').serialize(),
                        tryCount : 0,
                        retryLimit : 3,
                        timeout: 3500,
                        success: function () {
                            $('#success').fadeIn();
                            $('#submit-id-submit').removeAttr('disabled').val("Inscrire l'élève");
                            lock = false;
                        },
                        error: function (xhr, textStatus, errorThrown) {
                            if (textStatus == 'timeout') {
                                this.tryCount++;
                                if (this.tryCount <= this.retryLimit) {
                                    // try again.
                                    $.ajax(this);
                                    return;
                                }
                            }
                            $('#submit-id-submit').removeAttr('disabled').val("Désolé, une erreur s'est produite. Réessayer dans quelques instants…");
                            lock = false;
                        }
                    });
                } else {
                    $("#fail_exist").fadeIn();
                    $('#submit-id-submit').removeAttr('disabled').val("Inscrire l'élève");
                }
            });
        } else {
            $('#submit-id-submit').removeAttr('disabled').val("Inscrire l'élève");
        }
        lock = false;
    });
</script>

templates/slas/list.html
{% extends "core/base.html" %}

{% block content %}
<div class="container">
    <div class="row" style="padding-bottom:5px">
        <div class="form-inline col-sm-6" >
                <div class="form-group">
                    <label for="select-activity" class="control-label ">Activité : </label>
                        <select id="select-activity" class="form-control">
                            <option value="-1">Tous</option>
                            {% for g in activities %}
                            <optgroup label="{{ g.day }} {{ g.slot.0 }}">
                                {% for a in g.activities.0 %}
                                <option value="{{ a.id }}" {% if request.GET.activity == a.id|stringformat:"i" %}selected{% endif %}>{{ a.name }}</option>
                                {% endfor %}
                            </optgroup>
                            <optgroup label="{{ g.day }} {{ g.slot.1 }}">
                                {% for a in g.activities.1 %}
                                <option value="{{ a.id }}" {% if request.GET.activity == a.id|stringformat:"i" %}selected{% endif %}>{{ a.name }}</option>
                                {% endfor %}
                            </optgroup>
                            {% endfor %}
                        </select>
                </div>
        </div>
        <div class="col-sm-4">
            <a class="btn btn-default" href="{% url 'slas:data' %}" role="button">Exporter vers un fichier excel</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">Inscriptions aux activités SLAS</div>
                <ul class="list-group">
                    {% for i in inscriptions %}
                    <li class="list-group-item" style="padding-bottom: 30px">
                        <strong>{{ i.activity.name }}</strong>
                            {% if i.activity.day == 'Mercredi' %}
                                (14h20 à 16h10)
                            {% elif i.activity.day == 'vendredi' %}
                                {% if i.activity.slot == 0 %}(15h20 à 16h10{% else %}(16h20 à 17h10{% endif %}
                            {% else %}
                                {% if i.activity.slot == 0 %}(16h20 à 17h10{% else %}(17h10 à 18h00{% endif %}
                            {% endif %}
                         {{ i.activity.day }}) :
                        {{ i.student_first_name }} {{ i.student_surname }} ({{ i.classe }}).
                        <a class="btn btn-default btn-xs pull-right" href="#suite{{ i.pk }}" data-toggle="collapse">+Info</a>
                        <div class="pull-right" style="margin-right:10px">
                            <label class="checkbox-inline">
                                <input class="answered" type="checkbox" id="answered-{{ i.pk }}" value="{{ i.pk }}"
                                       {% if i.answered %}checked{% endif %}
                                autocomplete=off> Répondu
                            </label>
                            <label class="checkbox-inline">
                                <input class="payed" type="checkbox" id="payed-{{ i.pk }}" value="{{ i.pk }}"
                                       {% if i.payed %}checked{% endif %}
                                autocomplete=off> Payé
                            </label>
                        </div>
                        <div class="collapse" id="suite{{ i.pk }}">
                            <dl class="dl-horizontal">
                                <dt>Née le :</dt><dd>{{ i.birth }}</dd>
                                <dt>Famille :</dt><dd>{{ i.family }}</dd>
                                <dt>Paiement :</dt><dd>{{ i.resp_payement }}</dd>
                                <dt>Responsable :</dt><dd>{{ i.resp_first_name }} {{ i.resp_surname }}</dd>
                                <dt>Adresse :</dt><dd>{{ i.resp_address }}</dd>
                                <dt>Email(s)</dt><dd>{{ i.resp_email }}{% if i.resp_email_2 %} et {{ i.resp_email_2 }}{% endif %}</dd>
                                <dt>Téléphones :</dt><dd>{{ i.resp_telephone }} et {{ i.resp_telephone_2 }}</dd>
                            </dl>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
    $("#select-activity").change(function () {
        activity = $(this).find(':selected').attr('value');
        location.href = "{% url 'slas:list' %}?activity=" + activity;
        });

    $(".payed").change(function () {
        var id = $(this).val();
        var checked = $(this).is(":checked") ? 1 : 0;
        $.get("{% url 'slas:payed_clean' %}/" + id + "/" + checked);
    });
    $(".answered").change(function () {
        var id = $(this).val();
        var checked = $(this).is(":checked") ? 1 : 0;
        $.get("{% url 'slas:answered_clean' %}/" + id + "/" + checked);
    });

</script>
{% endblock content %}